### PR TITLE
JAVA-37363 - enabled test

### PR DESCRIPTION
**Pull request by GaetanoPiazzolla**

### CODE REVIEW

**Comment by GaetanoPiazzolla** [comment]
retest this please

**Comment by GaetanoPiazzolla** [comment]
retest this please

**Comment by GaetanoPiazzolla** [comment]
retest this please

**Comment by GaetanoPiazzolla** [comment]
retest this please

**Comment by GaetanoPiazzolla** [comment]
retest this please

**Review by alvin577austria — APPROVED** [review]

**Pull request merged**
