### PR TITLE
update code snippet for command line argument

### PR DESCRIPTION
**Pull request by oluG4real**
update code snippet for command line argument

### CODE REVIEW

**Comment by lor6** [comment]
retest this please

**Comment by oluG4real** [comment]
Hi Loredana,

I have restarted it. Thank you.

Kind regards

**Comment by lor6** [comment]
retest this please

**Comment by lor6** [comment]
retest this please

**Comment by oluG4real** [comment]
Hi Loredana,

I have not been online for a while now, so sorry for late reply.

I am retesting it now, thank you

kind regards

**Comment by oluG4real** [comment]
I am on it.

**Pull request closed without merging**
