### PR TITLE
Fix test code for success

### PR DESCRIPTION
**Pull request by jneuhaus**
Two files needed updates so that tests
would complete successfully.

### CODE REVIEW

**Comment by eugenp** [comment]
Hey @jneuhaus - what JIRA is this part of?

**Comment by jneuhaus** [comment]
@eugenp I did not submit a bug in Jira for this. I made two modifications to make the tests pass, and submitted those changes as a pull request. Did I need to submit a bug report first?

**Comment by lor6** [comment]
Thanks @jneuhaus  We'll check the fix and merge it if everything looks ok.

**Comment by amit2103** [comment]
Hi @jneuhaus ,
I run UserRepositoryIntegrationTest test case with the existing code and its running successfully in my local. Can you give some description about the issue ?

**Comment by jneuhaus** [comment]
If you view diffs you should see a bad reference; however, it was minor and
possibly already fixed?

**Comment by lor6** [comment]
Hi @jneuhaus  We checked the tests and the syntax of the first query and everything is working ok. Since the first query is a native query, you may run into issues depending on the database you're using. Our example uses H2 database and the syntax is valid for it. 

Thanks.

**Pull request closed without merging**
