### PR TITLE
Add JSON Schema validation

### PR DESCRIPTION
**Pull request by ivanp81**

### CODE REVIEW

**Comment by tomjoebob** [comment]
This looks good, you just need to remove the .project, .cache-tests and .classpath files.

**Comment by tomjoebob** [comment]
This looks good, you just need to remove the .project, .cache-tests and .classpath files.

**Comment by tomjoebob** [comment]
Also, it looks like you have merge conflicts.

**Comment by ivanp81** [comment]
Removed file and conflict

**Pull request merged**
