### PR TITLE
BAEL-3817 - ThreadPoolTaskExecutor corePoolSize vs. maxPoolSize

### PR DESCRIPTION
**Pull request by markathomas**

### CODE REVIEW

**Comment by asif-anwar** [comment]
[retest this please]
Note: this comment is for CI build. No action required from the author

**Comment by asif-anwar** [comment]
[retest this build]
Note: this comment is for CI build. No action required from the author.

**Comment by asif-anwar** [comment]
[retest this please]
Note: this comment is for CI build. No action required from the author.

**Comment by asif-anwar** [comment]
[retest this please]
Note: this comment is for CI build. No action required from the author.

**Comment by asif-anwar** [comment]
[retest this please]

**Comment by markathomas** [comment]
Not sure what you mean, all the tests in my module pass.

**Pull request merged**
