### PR TITLE
Cleanup and function references

### PR DESCRIPTION
**Pull request by mrsoto**
Just tiny clean up and simplifications by function references and specialized assertions

### CODE REVIEW

**Comment by eugenp** [comment]
Hey @mrsoto - is this part of any JIRA?

**Comment by mrsoto** [comment]
No, it isn't

**Comment by lor6** [comment]
Thanks @mrsoto We'll check the fix and merge it if everything look ok

**Comment by lor6** [comment]
@amit2103  I'll merge the PR; let's add the update you mentioned afterwards

**Pull request merged**
