### PR TITLE
Delete the root element from the tree.

### PR DESCRIPTION
**Pull request by bi-**

### CODE REVIEW

**Comment by eugenp** [comment]
Hey @bi-  - what is this one about? Is it related to a specific JIRA?

**Comment by bi-** [comment]
Hi,

No jira issue, It just fixes the delete method. 

It updates the tree if the delete methods gets the same value as the root element holds, earlier it did not update it. See the test method.

**Comment by eugenp** [comment]
I see, thanks for clearing that up, @bi-  
Quick question - are you an author with the site?

**Comment by eugenp** [comment]
Oh, OK, thanks for clearing that up, @bi-  :)

**Comment by lor6** [comment]
Hi @bi-  Thanks for the PR. I want to merge but there's a conflict.

**Comment by bi-** [comment]
fixed, please check again.

**Comment by lor6** [comment]
@bi-  Merged, thank you.

**Pull request merged**
