### PR TITLE
Fix app in the load test tools comparison

### PR DESCRIPTION
**Pull request by slandelle**
Motivation:

The current implementation has performance issues and throughput decreases over time. This is likely causes by the lack of indexes on the h2 database. See the `findByXXX` repository methods.

Modifications:

Go with in memory maps with direct access by key instead of an h2 database.

Result:

Way faster and stable application under test.

On my test environment, Gatling outperforms JMeter (didn't try The Grinder):

```
Simulation com.baeldung.RewardsScenario completed in 23 seconds
Parsing log file(s)...
Parsing log file(s) done
Generating reports...

================================================================================
---- Global Information --------------------------------------------------------
> request count                                     499997 (OK=499997 KO=0     )
> min response time                                      0 (OK=0      KO=-     )
> max response time                                    461 (OK=461    KO=-     )
> mean response time                                     5 (OK=5      KO=-     )
> std deviation                                          6 (OK=6      KO=-     )
> response time 50th percentile                          4 (OK=4      KO=-     )
> response time 75th percentile                          5 (OK=5      KO=-     )
> response time 95th percentile                          7 (OK=7      KO=-     )
> response time 99th percentile                         13 (OK=13     KO=-     )
> mean requests/sec                                20833.208 (OK=20833.208 KO=-     )
---- Response Time Distribution ------------------------------------------------
> t < 800 ms                                        499997 (100%)
> 800 ms < t < 1200 ms                                   0 (  0%)
> t > 1200 ms                                            0 (  0%)
> failed                                                 0 (  0%)
================================================================================
```

```
$ apache-jmeter-5.3/bin/jmeter -Jjmeter.reportgenerator.overall_granularity=1000 -n -t TestPlan.jmx -l log.jtl -e -o ~/jmeter-reports
Creating summariser <summary>
Created the tree successfully using TestPlan.jmx
Starting standalone test @ Thu Oct 15 16:15:05 CEST 2020 (1602771305736)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary + 341050 in 00:00:24 = 14091.8/s Avg:     5 Min:     0 Max:   218 Err: 341050 (100.00%) Active: 100 Started: 100 Finished: 0
summary + 158950 in 00:00:08 = 20761.5/s Avg:     3 Min:     0 Max:   143 Err: 158950 (100.00%) Active: 0 Started: 100 Finished: 100
summary = 500000 in 00:00:32 = 15694.6/s Avg:     4 Min:     0 Max:   218 Err: 500000 (100.00%)
Tidying up ...    @ Thu Oct 15 16:15:37 CEST 2020 (1602771337657)
```

### CODE REVIEW

**Comment by slandelle** [comment]
Awesome, great work!

Feel free to give my map based version a try, just to make sure the h2 app is not the bottleneck. Otherwise, feel free to close this PR.

Thanks a lot for your help and patience with this!

**Comment by lor6** [comment]
@slandelle The time is slightly lower, but I'll keep the H2 version and include that in the text.

I've updated the article now: https://www.baeldung.com/gatling-jmeter-grinder-comparison, though it may take a few hours to see the latest version.

Thanks for all the help.

FYI, the "click here" link on this page: https://gatling.io/open-source/start-testing/ leads to the 3.3.1 zip. The "Download Gatling" link lower on the page here: https://gatling.io/open-source/ leads to the latest 3.4.1 version.

**Comment by slandelle** [comment]
> I've updated the article now: https://www.baeldung.com/gatling-jmeter-grinder-comparison, though it may take a few hours to see the latest version.

Thanks a lot!

> FYI, the "click here" link on this page: https://gatling.io/open-source/start-testing/ leads to the 3.3.1 zip. The "Download Gatling" link lower on the page here: https://gatling.io/open-source/ leads to the latest 3.4.1 version.

Oh, thanks a lot. Fixed!

**Comment by slandelle** [comment]
sorry to bother, but it looks like the updated article is still not online. Manual validation? Also, have you updated the performance grades in 5?

**Comment by lor6** [comment]
Hi @slandelle  It takes a while for the cache to update, though I'm not sure of the exact time. You could try clearing cache/incognito window or a different computer/phone if you can.

Yes, section 5 is updated as well.

**Comment by slandelle** [comment]
> You could try clearing cache/incognito window

Already tried with no luck :) I'll let you know, thanks!

**Pull request closed without merging**
