### PR TITLE
Split the first 2 modules: java-dates-conversion and java-dates-string.

### PR DESCRIPTION
**Pull request by alessiostalla**
As the branch name says, this is about BAEL-16646.

### CODE REVIEW

**Comment by alessiostalla** [comment]
Note: one article (https://www.baeldung.com/java-override-system-time) has been added in the meantime. It should be moved but I think a separate issue is emerging for articles like this.

**Comment by asif-anwar** [comment]
[retest this please]
Note: this comment is for CI build. No action required from the author.

**Comment by jzheaux** [comment]
test this please

**Comment by jzheaux** [comment]
test this please

**Pull request merged**
