### PR TITLE
[BAEL-16642] Split or move guava-collections module

### PR DESCRIPTION
**Pull request by catalin-burcea**

### CODE REVIEW

**Comment by catalin-burcea** [comment]
test

**Comment by asif-anwar** [comment]
[retest this please]
Note: This comment is for the CI build, no action required from the author

**Comment by asif-anwar** [comment]
[retest this please]
Note: This comment is for the CI build, no action required from the author

**Comment by asif-anwar** [comment]
[retest this please]
Note: This comment is for the CI build, no action required from the author

**Pull request merged**
