### PR TITLE
BAEL-8202: maven spotless plugin

### PR DESCRIPTION
**Pull request by etrandafir93**

### CODE REVIEW

**Comment by vinipx** [comment]
retest this please

**Comment by etrandafir93** [comment]
> retest this please

@vinipx fixed now. It is a messy interaction with the parent pom which has some customizations of the maven-verifier, for a different article. I have fixed it now - I've noticed that the other modules had the same issue and dealt with it in the same way.

**Comment by vinipx** [comment]
> > retest this please
> 
> @vinipx - I've fixed it now. It is a messy interaction with the parent pom which has some customizations of the maven-verifier, for a different article. I have fixed it now - I've noticed that the other modules had the same issue and dealt with it in the same way.

just to explain - the "_retest this now_" is a command we use to trigger Jenkins build run

**Comment by etrandafir93** [comment]
> > > retest this please
> > 
> > 
> > @vinipx - I've fixed it now. It is a messy interaction with the parent pom which has some customizations of the maven-verifier, for a different article. I have fixed it now - I've noticed that the other modules had the same issue and dealt with it in the same way.
> 
> just to explain - the "_re test this now_" is a command we use to trigger Jenkins build run

yes - but the test was still failing. I needed to add this to fix it:
https://github.com/eugenp/tutorials/pull/16982/commits/0936a305b0eb87d5893eabee287b2f5468d91c09

**Pull request merged**
