### PR TITLE
JAVA-20464 Fix failing tests in hibernate-exceptions module

### PR DESCRIPTION
**Pull request by timis1**

### CODE REVIEW

**Comment by KingsleyAmankwah** [comment]
@timis1  I'm working on the hibernate-mapping-2 module. I'm facing these errors any help with that? let me know if you're open to help
Continuous Integration JDK9 and Above - Jenkins — The Jenkins CI build failed

**Comment by timis1** [comment]
> @timis1 I'm working on the hibernate-mapping-2 module. I'm facing these errors any help with that? let me know if you're open to help Continuous Integration JDK9 and Above - Jenkins — The Jenkins CI build failed

@KingsleyAmankwah after the integration should fix that errors. I fixed the tests from hibernate-exceptions and hibernate-jpa. Please let me knwo how I can help you further.

**Comment by KingsleyAmankwah** [comment]
Oh okay thank you

**Comment by timis1** [comment]
> Oh okay, thank you. I'm told to follow these guidelines below but Im finding it difficult any help with that
> 
> ** If the module uses Java 9 or above, then you have to add it to the _-jdk9-and-above profiles in the main pom otherwise, the build will fail, as it uses JDK 8 for the default-_ profiles if the module is already present in one of the parents that use JDK 8, it should be removed from there as well, and only added to the right profiles in the main pom
> 
> Below is my PR link #13875

@KingsleyAmankwah as far as I rember I ran yesterday the tests from hibernate-mapping-2 and ran successfully. The module hibernate-mapping-2 runs with jdk17 and hibernate 6.2. I will try to looke over the errors later today or tomorrow.

**Comment by KingsleyAmankwah** [comment]
Thank you very much @timis1

**Pull request merged**
