### PR TITLE
JAVA-18142 New JHipster-6 module for JDK 11

### PR DESCRIPTION
**Pull request by anastasiosioannidis**

### CODE REVIEW

**Comment by anastasiosioannidis** [comment]
retest this please

**Comment by anastasiosioannidis** [comment]
retest this please

**Comment by anastasiosioannidis** [comment]
retest this please

**Comment by anastasiosioannidis** [comment]
retest this please

**Comment by anastasiosioannidis** [comment]
retest this please

**Comment by anastasiosioannidis** [comment]
retest this please

**Comment by anastasiosioannidis** [comment]
retest this please

**Comment by asif-anwar** [comment]
retest this please

**Pull request merged**
