### PR TITLE
uploaded guide-to-bean-scopes inspring-all

### PR DESCRIPTION
**Pull request by rOmAn2193**
Added guide to bean scopes source code to spring-all folder

### CODE REVIEW

**Comment by pivovarit** [comment]
@rOmAn2193 the last change is empty too

**Comment by rOmAn2193** [comment]
The last one worked

**Comment by rOmAn2193** [comment]
I am using Eclipse but I am not using the formatter. If you need me to, I will. The PR supposed to have 4 files, class files won't upload, neither do the jar files I used to import the required libraries.

Thanks,
Roman

**Comment by pivovarit** [comment]
@rOmAn2193 you threw those again randomly next to the main structure, can you create runnable JUnit tests for those?

**Pull request closed without merging**
