### PR TITLE
BAEL-378 A Guide to Activiti with Java

### PR DESCRIPTION
**Pull request by mansi2392**

### CODE REVIEW

**Comment by pivovarit** [comment]
@mansi2392 @yetanotherallisonf shouldn't this one be merged?

**Comment by mansi2392** [comment]
Yes @pivovarit, let me rebase it to fix the build issue.

**Comment by mansi2392** [comment]
Hey @pivovarit , should we merge this? So that I can commit the code for my next article.

**Comment by mansi2392** [comment]
@pivovarit , @yetanotherallisonf , can we merge this now? The article is already live. 
Also I need to commit code for my next article.

**Pull request merged**
