### PR TITLE
BAEL-2033 moved tutorial files

### PR DESCRIPTION
**Pull request by MrSamMillington**

### CODE REVIEW

**Comment by jzheaux** [comment]
Sam, it looks like the build is failing. Can you double check please? Sometimes it's just a checkstyles error. Thanks!

**Comment by jzheaux** [comment]
The Travis log says "core-java-8: You have 1 PMD violation". See what you get when you run the entire build locally.

**Comment by MrSamMillington** [comment]
Weird, when I run the build locally I get an issue in the core-java module:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project core-java: Compilation failure
[ERROR] /D:/tutorials/core-java/src/main/java/com/baeldung/classloader/PrintClassLoader.java:[3,27] package com.sun.javafx.util does not exist
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :core-java

**Comment by MrSamMillington** [comment]
I found the root of the PMD violation, (the names needed to end with UnitTest), and the module builds correctly on my local machine. However, the build failed again with the following: 

[ERROR] Failed to execute goal on project deltaspike: Could not resolve dependencies for project com.baeldung:deltaspike:war:1.0: Failed to collect dependencies at org.jboss:jandex:jar:1.2.5.Final-redhat-1: Failed to read artifact descriptor for org.jboss:jandex:jar:1.2.5.Final-redhat-1: Could not transfer artifact org.jboss:jandex:pom:1.2.5.Final-redhat-1 from/to redhat-repository-techpreview (https://maven.repository.redhat.com/techpreview/all/): Failed to transfer file: https://maven.repository.redhat.com/techpreview/all/org/jboss/jandex/1.2.5.Final-redhat-1/jandex-1.2.5.Final-redhat-1.pom. Return code is: 500 , ReasonPhrase:Internal Server Error. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :deltaspike

**Pull request closed without merging**
