### PR TITLE
JAVA-31570:  Changes made for fixing test failures with a named param…

### PR DESCRIPTION
**Pull request by Bipinkumar27**
…eter

### CODE REVIEW

**Review by harry9656 — COMMENTED** [review]
@alvin577austria This change will have second order effects. Please consider them before merging. A would suggest for a more "local" fix then changing the parent-boot-3.

**Comment by alvin577austria** [comment]
I agree, since parent-boot-3 is being used by other modules it would be best as of this moment to fix the failing test specific to the module.

**Comment by alvin577austria** [comment]
> I agree, since parent-boot-3 is being used by other modules it would be best as of this moment to fix the failing test specific to the module.

**Comment by alvin577austria** [comment]
I have closed this PR.
I checked spring-web-modules\spring-rest-http\pom.xml and it seems it was modified two days ago with this
https://github.com/eugenp/tutorials/pull/15897/files#diff-44fdff59d9f4b124fcc7f3a63c421b00a8e2c7ee20235214f302e53e49108403

This change have fixed the failing test in this module.

**Pull request closed without merging**
