### PR TITLE
added karate for rest-api & json / xml testing

### PR DESCRIPTION
**Pull request by ptrthomas**
This is an exact port of the REST-assured examples, with some additions in cases where Karate has better support for XML (for e.g. XPath) and JSON (e.g. schema-like and regex) validation.

The README contains links to the [Karate home page](https://github.com/intuit/karate) as well as some good references and tutorials.

Do let me know if you need more information or changes !

### CODE REVIEW

**Comment by pivovarit** [comment]
@ptrthomas I am doing a PR cleanup - is this one related to any of the articles?

**Comment by ptrthomas** [comment]
@pivovarit not directly, I did this more as a comparison with REST-assured and this article: http://www.baeldung.com/rest-assured-tutorial

I hope there could be an article on Karate in the future. In the meantime, if the above article is updated with a note at the end or something, that would be great.

**Comment by pivovarit** [comment]
@ptrthomas well, it does not make much sense to merge code without having any links to it. This is your lib, right? You could always write a guest article if you want. Just let us know.

**Comment by ptrthomas** [comment]
@pivovarit yes, I am interested in contributing a guest article. can you let me know how to go about it ?

**Pull request closed without merging**
