### PR TITLE
Caching tests with abstract classes

### PR DESCRIPTION
**Pull request by madmanx5**
I added a rest controller and a resource scan for the caching package to
align with my setup, now when accessing  the restcontroller via
/cachetest I'm getting a "java.lang.IllegalStateException: No cache
could be resolved for " Exception

### CODE REVIEW

**Comment by eugenp** [comment]
Hey @madmanx5 - can you please remind me what this was in relation to? I'm afraid I can't quite remember the context of the change. 
Thanks, 
Eugen.

**Comment by madmanx5** [comment]
Hey Eugen,

this was your last comment on the matter:

http://www.baeldung.com/spring-cache-tutorial#comment-2660787902

I've changed your code a bit so you get the same exception as me in my
setup.

Thanks,
Matthias

2016-05-28 22:20 GMT+02:00 Eugen <notifications@github.com>:

**Comment by pivovarit** [comment]
@eugenp can we close this one?

**Comment by madmanx5** [comment]
Hey Eugen,

did you have the chance to look at the issue? Can I do something to assist
you? We're still searching for a solution.

Thanks,
Matthias

2016-05-30 10:26 GMT+02:00 Matthias Dietl <matthias.dietl@gmail.com>:

**Pull request closed without merging**
