### PR TITLE
BAEL-7636 Add the missing plugin versions in the tutorial repo

### PR DESCRIPTION
**Pull request by dkapil**
-Added missing plugin versions

### CODE REVIEW

**Comment by dkapil** [comment]
Hey @lor6 ,
Can this https://stackoverflow.com/questions/4856307/when-maven-says-resolution-will-not-be-reattempted-until-the-update-interval-of be related?

**Comment by lor6** [comment]
@dkapil  I tried to restart the build after 24h. Still failing :(

**Comment by dkapil** [comment]
@lor6 so spring-swagger-codegen-app module can not find spring-swagger-codegen-client module.
I added an extra line in readme.md of spring-swagger-codegen-client so that its build can be triggered in travis and it may get available for spring-swagger-codegen-app. Let's see...

**Comment by dkapil** [comment]
@lor6 It worked. :+1:

**Pull request merged**
